# Generated by Django 5.0.2 on 2024-03-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=255)),
                ('short_url', models.CharField(max_length=10)),
                ('alias', models.CharField(max_length=7)),
            ],
        ),
    ]
